set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Bundle 'bling/vim-airline'
Bundle 'tpope/vim-fugitive'
" vim rails
Bundle 'tpope/vim-rails.git'
" ruby debugger
Bundle 'astashov/vim-ruby-debugger'
" comment shortcuts
Bundle 'tomtom/tcomment_vim'
" Colortheme solarized
Bundle 'altercation/vim-colors-solarized'
" Colortheme molokai
Bundle 'tomasr/molokai'
" Colortheme Darkmate
Bundle 'yearofmoo/Vim-Darkmate'
" ruby support
Bundle 'vim-ruby/vim-ruby'
" Sourround your code
Bundle 'tpope/vim-surround'
" auto add end keyword to ruby blocks
Bundle 'tpope/vim-endwise'
" Autogen pairs
Bundle 'jiangmiao/auto-pairs'
" Tab completions
"Bundle 'ervandew/supertab'
" plugin on GitHub repo
Bundle 'kchmck/vim-coffee-script'
" Fuzzy finder for vim (CTRL-P)
Bundle 'kien/ctrlp.vim'

Bundle 'editorconfig/editorconfig-vim'
" Ruby Tests
" Bundle 'skalnik/vim-vroom'
" Running tests in tmux session
" Bundle 'tpope/vim-dispatch'
" RVM
Bundle 'tpope/vim-rvm'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
Bundle 'nono/vim-handlebars'
" file tree
Bundle 'scrooloose/nerdtree'
" commenting code
Bundle 'scrooloose/nerdcommenter'
Bundle 'valloric/youcompleteme'
Bundle 'scrooloose/syntastic'
" Vim Javascript
Bundle 'pangloss/vim-javascript'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'nathanaelkane/vim-indent-guides'
" Angular
Bundle 'burnettk/vim-angular'
" Close Tags
Bundle 'vim-scripts/closetag.vim'
" Templates in vim
Bundle 'aperezdc/vim-template'
Bundle 'majutsushi/tagbar'
Bundle 'wavded/vim-stylus'
Bundle 'digitaltoad/vim-jade'
filetype plugin indent on
call vundle#end()            " required
filetype plugin indent on    " required

set autoindent

filetype plugin indent on
" Ruby stuff: Thanks Ben :)
" ================
syntax on                 " Enable syntax highlighting
filetype plugin indent on " Enable filetype-specific indenting and plugins

augroup myfiletypes
	" Clear old autocmds in group
	autocmd!
	" autoindent with two spaces, always expand tabs
	autocmd FileType ruby,eruby,yaml,markdown,cucumber set ai sw=2 sts=2 et
augroup END
" ================
"
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_coffee_checkers = ['coffeelint']
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_save = 1
" javascript stuff
let g:angular_source_directory = "app/scripts"
let g:angular_test_directory = 'test/specs'

autocmd BufNewFile,BufRead *.coffee set filetype=coffee
autocmd BufNewFile,BufRead *.styl set filetype=stylus
autocmd BufNewFile,BufRead *.jade set filetype=jade
set foldmethod=syntax

syntax enable
"set background=dark
"let g:molokai_original=1
"let g:molokai_termcolors=256
"let g:rehash256=1
"colorscheme molokai

colorscheme darkmate

set nu

set wildmode=longest,list,full
set wildmenu

filetype plugin on
 set grepprg=grep\ -nH\ $*
 filetype indent on
 let g:tex_flavor='latex'

 syntax on

" Airlinebar config
let g:airline_theme='luna'
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
set laststatus=2

map <F7> :NERDTreeToggle<CR>
map <F8> :TagbarToggle<CR>

" inoremap <leader>; <C-o>A;

inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

" Tab Mappings

nnoremap th  :tabfirst<CR>
nnoremap tj  :tabnext<CR>
nnoremap tk  :tabprev<CR>
nnoremap tl  :tablast<CR>
nnoremap tt  :tabedit<Space>
nnoremap tn  :tabnext<Space>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>
" Alternatively use
"nnoremap th :tabnext<CR>
"nnoremap tl :tabprev<CR>
"nnoremap tn :tabnew<CR>
" Auto nerdtree on start
" autocmd vimenter * NERDTree

" no ugly line wrap
set nowrap

" vim-latexsuite uses pdflatex by defauld to compile .tex documents
filetype plugin on
filetype indent on
au BufEnter *.tex set autowrite
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats = 'pdf'
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode $*'
let g:Tex_GotoError = 0
let g:Tex_ViewRule_pdf = 'evince'

au BufNewFile,BufRead,BufEnter   *.wiki    setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   *.md      setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   *.txt     setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   *.tex     setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   README    setlocal spell    spelllang=en_us

set history=200
