set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
" nice looking bottom line
Bundle 'bling/vim-airline'
" Git tools
Bundle 'tpope/vim-fugitive'
" vim rails
Bundle 'tpope/vim-rails.git'
" ruby debugger
Bundle 'astashov/vim-ruby-debugger'
" comment shortcuts
Bundle 'tomtom/tcomment_vim'
" Colortheme solarized
Bundle 'altercation/vim-colors-solarized'
" Colortheme molokai
Bundle 'tomasr/molokai'
" ruby support
Bundle 'vim-ruby/vim-ruby'
" Sourround your code
Bundle 'tpope/vim-surround'
" auto add end keyword to ruby blocks
Bundle 'tpope/vim-endwise'
" Autogen pairs
Bundle 'jiangmiao/auto-pairs'
" Tab completions
"Bundle 'ervandew/supertab'
" plugin on GitHub repo
Plugin 'kchmck/vim-coffee-script'
" Fuzzy finder for vim (CTRL-P)
Bundle 'kien/ctrlp.vim'
" Ruby Tests
Bundle 'skalnik/vim-vroom'
" Running tests in tmux session
Bundle 'tpope/vim-dispatch'
" RVM
Bundle 'tpope/vim-rvm'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
Bundle 'nono/vim-handlebars'
" file tree
Bundle 'scrooloose/nerdtree'
" commenting code
Bundle 'scrooloose/nerdcommenter'
" Make GVim colorschemes work in Terminal-Vim
Bundle 'godlygeek/csapprox'
" Autocomplete
Bundle 'valloric/youcompleteme'
" Syntax Checker
Bundle 'scrooloose/syntastic'
" Vim Web
Bundle 'mattn/webapi-vim'
" Gists
Bundle 'mattn/gist-vim'
" latex
Bundle 'gerw/vim-latex-suite'
" Grammar checker
Bundle 'vim-scripts/languagetool'
" Vim Javascript
Bundle 'pangloss/vim-javascript'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'nathanaelkane/vim-indent-guides'
Bundle 'Raimondi/delimitMate'
" Vim Jasmine
Bundle 'claco/jasmine.vim'
" Vim Snippets
Bundle 'honza/vim-snippets'
" Dependencies for Spnipped Engine
Bundle 'marcweber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'garbas/vim-snipmate'
" Close Tags
Bundle 'vim-scripts/closetag.vim'
filetype plugin indent on
call vundle#end()            " required
filetype plugin indent on    " required

set autoindent

filetype plugin indent on
" Ruby stuff: Thanks Ben :)
" ================
syntax on                 " Enable syntax highlighting
filetype plugin indent on " Enable filetype-specific indenting and plugins

augroup myfiletypes
	" Clear old autocmds in group
	autocmd!
	" autoindent with two spaces, always expand tabs
	autocmd FileType ruby,eruby,yaml,markdown,cucumber set ai sw=2 sts=2 et
augroup END
" ================
"
let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_jshint_exec = '/home/roman/npm/bin/jshint'
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_save = 1

" javascript stuff


syntax enable
set background=dark
let g:molokai_original=1
let g:molokai_termcolors=256
let g:rehash256=1
colorscheme molokai

set nu

set wildmode=longest,list,full
set wildmenu

filetype plugin on
 set grepprg=grep\ -nH\ $*
 filetype indent on
 let g:tex_flavor='latex'

 syntax on

" Airlinebar config
let g:airline_theme='luna'
let g:airline_powerline_fonts=1
set laststatus=2


inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

" Auto nerdtree on start
" autocmd vimenter * NERDTree

" no ugly line wrap
set nowrap

" vim-latexsuite uses pdflatex by defauld to compile .tex documents
filetype plugin on
filetype indent on
au BufEnter *.tex set autowrite
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats = 'pdf'
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode $*'
let g:Tex_GotoError = 0
let g:Tex_ViewRule_pdf = 'evince'

au BufNewFile,BufRead,BufEnter   *.wiki    setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   *.md      setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   *.txt     setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   *.tex     setlocal spell    spelllang=de_de
au BufNewFile,BufRead,BufEnter   README    setlocal spell    spelllang=en_us

set history=200
